### ISSUE TITLE
Ldos.freqs() not working in 1.16.1

### ISSUE THREAD

**Issue by domeeneka** [NanoComp/meep#1416]
I am simulating circular grating cavity in cylindrical coordinates (https://github.com/domeeneka/Meep/blob/master/test.py). I observed that the latest Meep release (I thinks it's 1.16.1?) has a problem with accessing freqs() of Ldos while it works just fine with older 1.12.0 version. In the code, the ldos_instance.freqs() gives an error 'function' object has no attribute '__swig_getmethods__'. 

On the other hand, the older version gives errors when it comes to near field to far-field function (what():  meep: only 2d or 3d far-field computation is supported) and add_dft_fields() (add_dft_fields() missing 2 required positional arguments: 'freq_max' and 'nfreq' or in method 'fields_add_dft_fields', argument 5 of type 'double' if those two are added). While it makes more sense (functions not working for old releases getting fixed in newer ones), it forces me to change the environments for different pieces of codes. 

Is there any way to make the Ldos.freqs() work in the latest release?

**Comment by oskooi** [comment]
#1156 changed the `freqs()` member function of the `Ldos` object to [`get_ldos_freqs()`](https://meep.readthedocs.io/en/latest/Python_User_Interface/#ldos-spectra). This changed first appeared in [version 1.14](https://github.com/NanoComp/meep/releases/tag/v1.14.0).
